Controllers/ForumController.cs
using ForumSystem.Exceptions;
using ForumSystem.Models;
using ForumSystem.Repositories;
using ForumSystem.Services;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace ForumSystem.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForumDataService _forumDataService;
        public ForumController(IForumDataService forumDataService)
        {
            _forumDataService = forumDataService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new HomeVeiwModel
            {
                Posts = _forumDataService.ShowAllPosts(),
                registredUsers = _forumDataService.GetTotalUsersCount()


            };
          //  var posts = _forumDataService.ShowAllPosts();
            return View(viewModel);
        }

        //[HttpGet]
        //public IActionResult Details(int id)
        //{

        //    //try
        //    //{
        //    //    Post post = _forumDataService.GetPostByPostId(id);
        //    //    return View(post);
        //    //}
        //    //catch (EntityNotFountException ex)
        //    //{
        //    //    Response.StatusCode = StatusCodes.Status404NotFound;
        //    //    ViewData["Error"]=ex.Message;
        //    //    return View("Error");
        //    //}
        //}

        //[HttpGet]
        //public IActionResult Create() 
        //{
        //    var post = new PostViewModel();
        //    return View(post);
        //}

      /*  [HttpPost]
        public IActionResult Create(PostViewModel postViewModel) 
        { 

        }*/   //TODO
    }
}

Views/Forum/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ForumSystem.Models
@model PostViewModel

<html>
<head>
    <title>ForumSystem-Forum</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index">Home</a>
                |<a asp-controller="Forum" asp-action="Index">Forum</a>
            </h3>
        </div>
    </header>

    <div class="body-content">
        <h2>Create New Post</h2>

        <form asp-controller="Forum" asp-action="Create">
            <label asp-for="@Model.Post.Title">Title:</label><br>
            <input type="text" asp-for="@Model.Post.Title"><br>
            <label asp-for="@Model.Post.Content">Content:</label><br>
            <input type="text" asp-for="@Model.Post.Content"><br>
            <label asp-for="@Model.Post.IsPublic">Public:</label><br> 
            <input type="checkbox" asp-for="@Model.Post.IsPublic"><br>
            
            <input type="submit" value="Post">
        </form>


    </div>
        
</body>
</html>

Views/Forum/Details.cshtml
@using ForumSystem.Models
@model Post

<html>
<head>
    <title>ForumSystem-Details</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div>
            <h3>
                <a href="/Home/Index">Home</a>
                |<a href="/Forum/Index">Forum</a>
            </h3>
        </div>
    </header>
    <h2>@Model.PostID</h2>

    <p>@Model.Content</p>
    <p>@Model.PostDate</p>
  

</body>
</html>

Views/Forum/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using ForumSystem.Models
@model HomeVeiwModel

<html>
<head>
    <title>ForumSystem-Forum</title>
    <link href="~/css/style.css" rel="stylesheet"/>
</head>
<body>
        <div>
            <h3>
                <a asp-controller="Home" asp-action="Index">Home</a>
                |<a asp-controller="Forum" asp-action="Index">Forum</a>
            </h3>
        </div>
        <p>
            <a asp-controller="Forum" asp-action="Create"> Create New Post</a>
        </p>

     <table>
            <tr>
                <th>PostID</th>
                <th>Title</th>
                <th>Post-Date</th>
                <th>Active</th>
                <th>Open</th>
            </tr>
            @{
                foreach(var post in Model.Posts)
                {
                    <tr>
                        <td>@post.PostID</td>
                        <td>@post.Title</td>
                        <td>@post.PostDate</td>
                        <td>@post.IsActive</td>
                        <td><a href="@($"/Forum/Details/{post.PostID}")">Open</a></td>
                    </tr>
                }
            }
     </table>


</body>
</html>